{% set name = "dlt-pendulum" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dlt-hub/pendulum/archive/{{ version }}.tar.gz
  sha256: 9a0225a8e97399ad7c3930856d581093b65e36bb27c85c0da5a2575ddbaa9248

build:
  number: 0

requirements:
  build:
    - python
    - {{ stdlib('c') }} 
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - python-dateutil >=2.6
    - python-tzdata >=2020.1
    - cffi >=1.17

# E       AssertionError: assert None == 'Europe/Paris'
{% set deselect_tests = " --deselect=tests/tz/test_local_timezone.py::test_unix_symlink" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/tz/test_local_timezone.py::test_unix_etc_timezone_dir" %}

test:
  source_files:
    - tests
  imports:
    - pendulum
    - pendulum.__version__
    - pendulum.constants
    - pendulum.date
    - pendulum.datetime
    - pendulum.day
    - pendulum.duration
    - pendulum.exceptions
    - pendulum.formatting
    - pendulum.helpers
    - pendulum.interval
    - pendulum.locales
    - pendulum.mixins
    - pendulum.parser
    - pendulum.parsing
    - pendulum.time
    - pendulum.tz
    - pendulum.utils
  requires:
    - pip
    - pytest
    - pytz
    - time-machine
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_tests }}

about:
  home: https://github.com/dlt-hub/pendulum
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Python datetimes made easy
  description: |
    Drop-in replacement for the standard datetime class.
    It behaves exactly like it but with many improvements.
  dev_url: https://github.com/dlt-hub/pendulum
  doc_url: https://github.com/dlt-hub/pendulum/blob/master/README.rst

extra:
  recipe-maintainers:
    - rxm7706
